#!/usr/bin/env python3
"""Render the benchmark report from verified, retained measurements."""
import argparse,json
from pathlib import Path

NAMES={'tess_200s':'TESS 200 s','tess_gap':'TESS separated sectors','ztf':'ZTF g/r'}
METHODS={'bls_v1':'BLS v1','bls_v1_batch':'BLS v1 batch','bls_pypi':'BLS PyPI 0.2.5','bls_cpu':'BLS external CPU','bls_gpu':'BLS periodfind GPU','tls_v1':'TLS v1','gtls':'GTLS single','gtls_batch':'GTLS batch'}


def pct(x):return f'{100*x:.1f}%'
def seconds(x):return f'{x*1000:.3g} ms' if x<.1 else f'{x:.3g} s'


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--root',type=Path,required=True);a=ap.parse_args();r=a.root
    rec=json.loads((r/'recovery_analysis.json').read_text());tim=json.loads((r/'timing_analysis.json').read_text())
    comp=json.loads((r/'component_analysis.json').read_text());provenance=json.loads((r/'provenance-verification.json').read_text())
    assert rec['verification']['complete'] and tim['verification']['complete'] and comp['verification']['complete'] and provenance['complete']
    assert rec['verification']['arrays_verified'] and tim['verification']['arrays_verified']
    rr={(v['profile'],v['method']):v for v in rec['methods']};cc={(v['profile'],v['v1'],v['comparator']):v for v in rec['comparisons']}
    ratios={(v['profile'],v['mode'],v['v1'],v['comparator']):v for v in tim['ratios']}
    cohorts=json.loads((r/'runtime_cohort_analysis.json').read_text());assert cohorts['complete']
    text=['This benchmark measures the practical cuvarbase upgrade: prepared-array transit-search time, together with recovery on independent injections. The main figure shows both single-source latency and throughput for 16 distinct sources. Numerical speed ratios are qualified by the sensitivity actually demonstrated below.',
          '', 'The clearest supported upgrade is BLS on separated TESS sectors: **2.73× faster batch searches, or 10.18× faster fresh grid plus single-source search**, with the same 89/128 held-out transit detections as PyPI and a supported detection/false-positive comparison. Across the three examples, TLS batch searches are **93–284× faster than public GTLS**, but this experiment does **not establish equivalent detection sensitivity** for TLS. On ZTF, v1 detects more transits and also accepts more nulls. Those two findings belong together in any release claim.',
          '', '![Search time and independent recovery](benchmark_story.png)', '', '[Vector figure: PDF](benchmark_story.pdf) · [Editable SVG](benchmark_story.svg) · [Frozen protocol](PROTOCOL.md)', '',
          'Times include host preparation inside the API, transfers, periodograms and candidate ranking. Inputs, explicit period grids and GPU contexts are prepared before timing. Detrending, grid construction, imports, disk I/O, catalog vetting and idle time are outside these numbers. Initial setup and first API calls are retained in the timing table; these are fresh processes with already-populated disk caches, not pristine installations.', '',
          '| Workload | Comparison | Single-source speedup | Batch throughput speedup | Primary-period recovery | Detection + false positives |', '|---|---|---:|---:|---|---|']
    for p in NAMES:
        for v1,other in [('bls_v1','bls_pypi'),('bls_v1','bls_cpu'),('bls_v1','bls_gpu'),('tls_v1','gtls')]:
            ref='bls_v1_batch' if v1=='bls_v1' else v1;c=cc[p,ref,'gtls_batch' if other=='gtls' else other]
            verdict='Supported within 5 pp' if c['comparable_detection'] else 'Not established; see recovery difference'
            period_verdict='Noninferiority supported' if c['period_noninferior'] else 'Not established'
            other_name='GTLS upstream' if other=='gtls' else ('CPU '+('Astropy' if rr[p,other]['config']['backend']=='astropy' else 'periodfind')) if other=='bls_cpu' else METHODS[other]
            text.append(f"| {NAMES[p]} | {METHODS[v1]} vs {other_name} | {ratios[p,'single',v1,other]['speedup']:.2f}× | {ratios[p,'batch16',v1,other]['speedup']:.2f}× | {period_verdict} | {verdict} |")
    scheduling=json.loads((r/'cpu-operational-selection.json').read_text())
    if scheduling['selected_across_sources']:
        text+=['',f"For dense TESS, the CPU batch comparison uses Astropy workers across independent sources. On the tuning inputs this is {scheduling['source_scheduling_speedup']:.2f}× faster than the period-parallel single-source scheduling policy. All 384 independent calibration/held-out spectra and candidates are bit-identical under both schedules. Single-source timing retains period-parallel workers. [Scheduling evidence](cpu-operational-selection.json)."]
    text+=['','“Supported” means the one-sided 95% lower bound on paired v1-minus-comparator detection recall exceeds −5 percentage points, and the corresponding upper bound on the false-positive increase is below +5 points. This is a pooled result for the equally weighted SNR mixture in this experiment; inspect the per-SNR curves for tradeoffs. It does not mean identical algorithms, exactly equal recall, or a universal sensitivity guarantee. Unmarked speed ratios are measured timing differences; they must not be advertised as demonstrated equivalent-sensitivity speedups. “Not established” can reflect a measured loss or insufficient precision; it does not itself prove inferiority.', '',
           'Independent per-star searches can also require a new period grid. The following measurements put each release’s native Keplerian grid construction, endpoint trimming and one BLS search inside the timer. The fresh grids have bit-identical GPU float32 frequencies and duration bounds; the small float64 differences are retained. This separate boundary is relevant to QLP workloads that cannot reuse one grid across sources.', '',
           '| Workload | v1 fresh grid + search | PyPI fresh grid + search | Speedup | Single-source detection match |', '|---|---:|---:|---:|---|']
    tt={(v['profile'],v['method'],v['mode']):v for v in tim['timings']}
    for p in NAMES:
        v=tt[p,'bls_v1','fresh_grid'];old=tt[p,'bls_pypi','fresh_grid'];c=cc[p,'bls_v1','bls_pypi']
        text.append(f"| {NAMES[p]} | {seconds(v['seconds_per_source'])} | {seconds(old['seconds_per_source'])} | {old['seconds_per_source']/v['seconds_per_source']:.2f}× | {'Supported within 5 pp' if c['comparable_detection'] else 'Not established'} |")
    text+=['',
           '| Workload | Method | Correct primary period / 128 | Detected at correct period / 128 | False positives / 128 | Invalid held-out outputs |', '|---|---|---:|---:|---:|---:|']
    for p in NAMES:
        for m in METHODS:
            d=rr[p,m]
            text.append(f"| {NAMES[p]} | {METHODS[m]} | {d['period_recovered']} | {d['detected']} | {d['false_positives']} | {d['invalid_heldout']} |")
    masked=[f"{NAMES[p]} {METHODS[m]}: {d['masked_trials_calibration']} calibration / {d['masked_trials_heldout']} held-out trial periods, across {d['partial_spectra_calibration']} / {d['partial_spectra_heldout']} light curves" for (p,m),d in rr.items() if d['partial_spectra_calibration'] or d['partial_spectra_heldout']]
    if masked:
        text+=['','TLS can return a finite native candidate while representing trial periods with no admissible fit as NaN. These are distinct from an API exception or missing candidate. The experiment retains that native masking and calibrates the resulting score, and separately counts the masked trials: '+'; '.join(masked)+'. The full returned spectra and counts are retained.']
    text+=['', 'Each method’s detection threshold is the higher empirical 95th percentile of 128 independent calibration nulls. The held-out set contains 128 injections and 128 new nulls per observing pattern. The curves show 32 injections at each white-noise oracle SNR (6, 8, 10, 14), with 95% Wilson intervals. This SNR excludes the additional correlated residual and is neither native TLS SDE nor QLP pink-noise SNR. Achieved false-positive rates and paired differences are in [recovery_summary.csv](recovery_summary.csv), [recovery_by_snr.csv](recovery_by_snr.csv), and [paired_comparisons.csv](paired_comparisons.csv).', '',
           'Real cadence, controlled flux: the experiment uses public ZTF g/r times and relative errors, plus public QLP times/quality flags for one dense TESS sector and a controlled pair of separated sectors. Fluxes are simulated exposure-integrated batman transits with heteroscedastic Gaussian noise and an OU residual. Injections require at least five observed in-transit points and two observed events. Known band baselines and achromatic transits are supplied. These three cadence examples are not a random catalog sample, injections into observed flux, unconditional survey completeness, or a reproduction of the full current QLP pipeline.', '',
           'A long gap matters to timing because the longer baseline requires finer trial-period spacing to keep a transit aligned. TESS 200 s uses 4,133 BLS / 3,084 TLS periods; separated TESS sectors use 128,964 / 99,043; ZTF uses 423,781 / 312,064. BLS and TLS have different minimum periods, so comparisons are within each algorithm. A simulated sinusoid or noise does not invalidate a fixed-grid timing comparison on identical arrays; transits are needed here to establish recovery. GTLS’s mean-depth gate can also make flux values affect its execution time.', '',
           'Configuration selection used only 32 tuning injections per survey. The fastest complete choice within one recovery of the best in each family was retained, with close timings repeated. CPU candidates included Astropy, periodfind’s Rust implementation and fBLS; GPU BLS included periodfind. This identifies the strongest tested competitor for these workloads, not the fastest code that could exist. Selected versions, settings, exclusions and repeat evidence are in [selection.json](selection.json); operational choices are recorded separately when applicable.', '',
           'BLS gains come from reusing folded phase histograms for several phase offsets, a vectorized maximum-bin scan and grid generator, and a public batch API that amortizes per-source work. Both releases receive warmed kernels and reusable PyPI memory in this experiment; compilation caching is not credited as a cause of the remaining warm API ratio. Batch throughput has a separate recovery validation. Some tuned searches have different phase sampling and minimum-duration bounds, so the total upgrade ratio is not a pure kernel ablation. The separated-TESS PyPI comparison uses matching duration bounds and phase-pass counts. PyPI 0.2.5 documents `noverlap` as unimplemented in its fast kernel: the adapter uses the documented repeated `dphi` calls, public reusable memory, a GPU maximum and one final transfer. No installed package source is changed.', '',
           '| Selected BLS settings | v1 phase passes | PyPI phase passes | v1 minimum duration / central duration | PyPI minimum duration / central duration |', '|---|---:|---:|---:|---:|']
    for p in NAMES:
        aa=rr[p,'bls_v1']['config'];bb=rr[p,'bls_pypi']['config']
        text.append(f"| {NAMES[p]} | {aa['noverlap']} | {bb['noverlap']} | {aa.get('qmin_fac',.5):g} | {bb.get('qmin_fac',.5):g} |")
    text+=['','Both BLS releases use maximum duration 2 times the central duration and dlogq=0.1. The minimum-duration factor was among the tuning choices; the selected 0.25 values widen the initial QLP-inspired 0.5 lower bound. TLS v1 uses epoch oversampling 4 and 16 durations, with 50 candidates refined; its fractional-duration window is 0.5–2 times the central value. GTLS uses its documented fast mode, duration_grid_step=1.1 and stellar-radius bounds 0.5–2 solar radii at one solar mass. Those GTLS physical bounds do not make its discrete template-duration/epoch search identical to v1’s. These are selected benchmark settings, not a claim about the exact current QLP production configuration.', '',
           'The external BLS implementations have additional numerical differences. Astropy and periodfind accept scalar duration bounds, approximated here with 16 logarithmic period chunks covering the same density prior. periodfind searches brightening and dimming boxes, whereas cuvarbase/Astropy are configured for dimmings; its public output does not expose a dip-only switch. periodfind’s long-lightcurve GPU branch has a fixed 64-bin array, so the dense TESS comparison uses a valid capped setting. Unchecked larger-bin calls crashed and are excluded. fBLS native-grid pilots and failures remain in the evidence; failures and timeouts do not supply speedup denominators.', '',
           'TLS gains combine architecture and host orchestration. cuvarbase folds into weighted phase bins, evaluates integrated templates and analytically solves weighted depths, then refines a limited candidate set against observations. GTLS sorts phase-folded samples, represents template widths in observation counts, estimates depth from an unweighted window mean and template overshoot, and evaluates weighted residuals. Epoch/duration grids, geometry, refinement and SDE construction differ. These are related template searches, not numerically identical algorithms. The fast cuvarbase TLS engine predates phase 5; the whole gain cannot be attributed to that phase.', '',
           'The separate [TLS component audit](../tls-profile-20260908/README.md) demonstrates substantial avoidable GTLS dispatch overhead. On its two retained diagnostic inputs, batching two Python/CuPy host operations makes GTLS about 5.8× faster while retaining the best periods; one operation is bit-identical and the other changes chi-square by a few parts in 10⁶ in absolute units. Those diagnostic patches are not the released competitor in this figure. The main comparison uses the unmodified public API, including its fast mode when selected by tuning. The remaining API ratio cannot be interpreted as the speed of an otherwise identical residual kernel.', '',
           'The new component experiment repeats explanatory measurements on all three cadence examples, using a retained tuning injection. The table reports ordinary uninstrumented API medians; synchronized wall-phase fractions are kept separately. The BLS rows disable one feature while retaining scientific settings. The GTLS row enables the two diagnostic host-loop changes. These ablations are not released competitors, are not independent additive savings, and cannot be multiplied to explain the full release ratio.', '',
           '| Workload | Diagnostic change | Baseline time | Changed time | Changed / baseline time | Same primary period | Maximum spectrum difference |', '|---|---|---:|---:|---:|---|---:|']
    for row in comp['ablations']:
        text.append(f"| {NAMES[row['profile']]} | {row['meaning']} | {seconds(row['baseline_s'])} | {seconds(row['variant_s'])} | {row['variant_over_baseline']:.2f}× | {row['candidate_period_equal']} | {row['max_abs_power_difference']:.3g} ({row['power_units']}) |")
    fused=[v for v in comp['ablations'] if v['variant'].endswith('_unfused')]
    scatter=[v for v in comp['ablations'] if v['variant'].endswith('_no_scatter')]
    gtls=[v for v in comp['ablations'] if v['variant'].endswith('_both')]
    text+=['',f"The fusion ablation increases ordinary BLS API time by {min(v['variant_over_baseline'] for v in fused):.2f}–{max(v['variant_over_baseline'] for v in fused):.2f}×. Observation scattering does not demonstrate a benefit on these retained cases: disabling it reduces the measured median by {min(1-v['variant_over_baseline'] for v in scatter)*100:.0f}–{max(1-v['variant_over_baseline'] for v in scatter)*100:.0f}%. All these ablations retain the primary period, with small spectrum changes. They are three-repetition diagnostics on one tuning injection per cadence, not population sensitivity tests or a new optimized release.", '',
           'For GTLS, batching the two host loops improves the ordinary single-source API by '+', '.join(f"{NAMES[v['profile']]} {1/v['variant_over_baseline']:.2f}×" for v in gtls)+'. This is a demonstrated opportunity for upstream improvement; the figure uses the unmodified released interface. Residual-template evaluation and phase sorting remain after the loop changes. The remaining gap includes cuvarbase’s different search architecture and numerical approximation, so it cannot be advertised as a pure implementation speedup at identical sensitivity.']
    text+=['','The validation runs also provide an independent timing sanity check: mean GTLS batch time per injected source is about 3–5% greater than for null sources on these cadences. This is much smaller than the measured API ratio. It is not a causal signal-only ablation: the cohorts also contain independent missing-sample/noise draws and sequential timing variation. [Runtime by cohort](runtime_by_cohort.csv) · [Cohort ratios](runtime_cohort_ratios.csv).']
    varied=[v for v in tim['repetition_agreements'] if not v['candidate_numerically_equal']]
    if varied:
        assert all(v['calibrated_null_decision_equal'] for v in tim['repetition_agreements'])
        max_delta=max(v.get('power_max_abs_difference',0.) for v in tim['agreements'] if 'gtls' in v['job'])
        text+=['',f"Timing-output audit: {len(varied)} source/repetition results change their best period relative to the retained validation run, all in GTLS’s separated-sector batch configuration (two null sources). Every timed repetition returns a valid finite result, and every calibrated null accept/reject decision is unchanged. Other parts of the GTLS batch spectra change by up to {max_delta:.2f} native SDE units on these timing nulls. GTLS’s memory-dependent chunking and numerical variation mean full spectra and candidates must not be described as universally identical between calls. The full deltas are retained in [timing_analysis.json](timing_analysis.json). PyPI fresh-grid float64 period rounding differences are also recorded; those remain numerically equal at relative tolerance 10⁻¹²."]
    text+=['', '[component_phases.csv](component_phases.csv) gives measured phase times and fractions; [component_summary.csv](component_summary.csv) reports profiling overhead and instrumentation differences; [component_ablations.csv](component_ablations.csv) retains numerical changes. These are synchronized wall regions, including dispatch/wait overhead, not GPU kernel-busy traces. The native GTLS fast-mode spectrum is in SDE units, so its deltas must not be described as chi-square deltas.', '',
           '| Fraction of synchronized diagnostic API time | TESS 200 s | Separated TESS | ZTF g/r |', '|---|---:|---:|---:|']
    phase_index={(v['job'],v['phase']):v for v in comp['phases']}
    for label,method,phase_names in [
        ('v1 BLS: common host candidate ranking','bls_v1',['Common candidate ranking']),
        ('v1 BLS: synchronized GPU kernel launches','bls_v1',['GPU kernel launches (synchronized)']),
        ('PyPI BLS: host maximum-bin scan','bls_pypi',['Host maximum-bin scan']),
        ('GTLS: two host-loop regions','gtls_native',['GTLS row-wise flux prefix sums','GTLS duration-mask union']),
        ('GTLS: phase folding / sorting','gtls_native',['GTLS folding/sorting']),
        ('GTLS: residual kernel region','gtls_native',['GTLS transit residual kernel']),
        ('v1 TLS: coarse kernel region','tls_v1_native',['v1 coarse search kernel']),
        ('v1 TLS: CPU statistics / results','tls_v1_native',['v1 CPU statistics/results'])]:
        values=[sum(phase_index.get((f'component_{p}_{method}',name),{}).get('fraction_of_profile',0.) for name in phase_names) for p in NAMES]
        text.append('| '+label+' | '+' | '.join(pct(v) for v in values)+' |')
    text+=['','These fractions belong to separately instrumented calls on one tuning injection per cadence, not the main batch timing. Synchronization and sequential measurement variation change the total runtime (including shorter profiled calls on some small problems), so do not multiply these percentages by the headline timings. They locate plausible bottlenecks: GTLS host dispatch on large grids and host candidate/statistics work after cuvarbase’s fast kernels.', '',
           '| Workload | v1 grid construction | PyPI grid construction | Grid-only speedup |', '|---|---:|---:|---:|']
    comps={v['job']:v for v in comp['components']}
    for p in NAMES:
        v=comps[f'component_{p}_bls_v1']['grid_median_s'];old=comps[f'component_{p}_bls_pypi']['grid_median_s']
        text.append(f'| {NAMES[p]} | {seconds(v)} | {seconds(old)} | {old/v:.2f}× |')
    text+=['',
           'The earlier CPU TLS failures were concrete output/template edge cases in transitleastsquares 1.32. Sparse PS1/Gaia examples constructed a zero-sample transit template before searching. ZTF/Rubin completed the period search, then failed while constructing a zero-sample plotting model; ZTF had already found the correct 1.66894-day period. First-call failure times include compilation and are not successful CPU timings. This requested TLS comparison is v1 versus GTLS; those CPU failures are not converted to speed claims.', '',
           '| Workload | v1 BLS projected GPU cost / million | v1 TLS projected GPU cost / million | CPU hourly break-even for BLS |', '|---|---:|---:|---:|']
    for p in NAMES:
        ts={v['method']:v for v in tim['timings'] if v['profile']==p and v['mode']=='batch16'}
        text.append(f"| {NAMES[p]} | ${ts['bls_v1']['projected_gpu_usd_per_million']:.2f} | ${ts['tls_v1']['projected_gpu_usd_per_million']:.2f} | ${ratios[p,'batch16','bls_v1','bls_cpu']['cpu_break_even_hourly_usd']:.4f}/h |")
    text+=['', 'Costs use the actual A40 bundle price, $0.49/hour, and linearly project measured batch search time. A standalone CPU at the measured performance would need to cost below the listed break-even price to beat that GPU search cost. No standalone CPU rental was measured. These are search-only rental equivalents, not measured million-star jobs or complete QLP costs. Hardware: A40 and a 7.65-CPU-equivalent quota on an Intel Xeon Gold 6342 host; the 96 host logical CPUs are not the allocation.', '',
           'Provenance: frozen cuvarbase v1 commit `1032caf029570dc4841db1c594a2cbb1654e8fd8`; PyPI cuvarbase `0.2.5`; GTLS upstream commit `74e449c325792a763dde4fbffab98039c5e8c111`; periodfind commit `116b1b27c8db4c95035b5233efa6a1d21780afa5`. Actual PyPI cuvarbase has no TLS implementation. The legacy environment uses NumPy 1.23.5 / PyCUDA 2022.2.2 and the modern environment NumPy 2.2.6 / PyCUDA 2025.1.2: this measures usable software stacks, not an isolated package-source change. Full environment listings accompany the hardware records. periodfind’s CUDA architecture selection in setup.py was adapted to build on the A40; its numerical sources are unchanged.', '',
           'Source archives, per-job installed-source hashes, input/output SHA256 values, controller exit records and every full periodogram are retained. [provenance-verification.json](provenance-verification.json) checks frozen inputs, the actual validation worker/controller, installed code and exclusive final timing intervals. Auxiliary A40 nodes evaluate serial GTLS recovery only; their elapsed times never enter speed ratios. Analysis/plot helpers continued to evolve after the scientific settings and actual validation worker were frozen; source revisions are retained by hash. [timing_summary.csv](timing_summary.csv) records timing boundaries and repetitions, [speedups.csv](speedups.csv) derives ratios/costs, and the analysis JSON files retain paired success vectors.', '',
           'Reproduce from the retained inputs and selected configurations with `scripts/benchmark_transit_recovery/worker.py` in the pinned modern/legacy environments; run manifests sequentially with `controller.py`. Regenerate verified statistics with `analyze.py --verify-arrays` and `analyze_timings.py --verify-arrays`, then `plot_main.py` and `write_report.py`, each with `--root analysis/transit-recovery-20260908`. All cloud resources must be terminated after evidence collection; the final rental ledger records actual elapsed rental and verified termination.']
    ledger=r/'rental-ledger.json'
    if ledger.exists():
        cost=json.loads(ledger.read_text());assert cost['all_terminated']
        text+=['',f"All three A40 nodes have been terminated and verified absent. Estimated total RunPod rental for the retained benchmark campaigns is **${cost['estimated_total_usd']:.2f}**, including the earlier **${cost['prior_campaigns_usd']:.2f}** once, against the authorized **$50** limit. This is elapsed rental × quoted rate, not an invoice. [Rental and termination ledger](rental-ledger.json)."]
    rendered='\n'.join(text).replace('released competitor','public competitor').replace('unmodified released interface','unmodified public upstream interface')+'\n'
    (r/'README.md').write_text(rendered);print('Wrote README.md')


if __name__=='__main__':main()
