#!/usr/bin/env python3
"""Render the benchmark report from verified, retained measurements."""
import argparse,json
from pathlib import Path

NAMES={'tess_200s':'TESS 200 s','tess_gap':'TESS separated sectors','ztf':'ZTF g/r'}
METHODS={'bls_v1':'BLS v1','bls_v1_batch':'BLS v1 batch','bls_pypi':'BLS PyPI 0.2.5','bls_cpu':'BLS external CPU','bls_gpu':'BLS periodfind GPU','tls_v1':'TLS v1','gtls':'GTLS'}


def pct(x):return f'{100*x:.1f}%'
def seconds(x):return f'{x*1000:.3g} ms' if x<.1 else f'{x:.3g} s'


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--root',type=Path,required=True);a=ap.parse_args();r=a.root
    rec=json.loads((r/'recovery_analysis.json').read_text());tim=json.loads((r/'timing_analysis.json').read_text())
    assert rec['verification']['complete'] and tim['verification']['complete']
    rr={(v['profile'],v['method']):v for v in rec['methods']};cc={(v['profile'],v['v1'],v['comparator']):v for v in rec['comparisons']}
    ratios={(v['profile'],v['mode'],v['v1'],v['comparator']):v for v in tim['ratios']}
    text=['This benchmark measures the practical cuvarbase upgrade: prepared-array transit-search time, together with recovery on independent injections. The main figure shows both single-source latency and throughput for 16 distinct sources. Numerical speed ratios are qualified by the sensitivity actually demonstrated below.',
          '', '![Search time and independent recovery](benchmark_story.png)', '', '[Vector figure: PDF](benchmark_story.pdf) · [Editable SVG](benchmark_story.svg) · [Frozen protocol](PROTOCOL.md)', '',
          'Times include host preparation inside the API, transfers, periodograms and candidate ranking. Inputs, explicit period grids and GPU contexts are prepared before timing. Detrending, grid construction, imports, disk I/O, catalog vetting and idle time are outside these numbers. Initial setup and first API calls are retained in the timing table; these are fresh processes with already-populated disk caches, not pristine installations.', '',
          '| Workload | Comparison | Single-source speedup | Batch throughput speedup | Held-out detection match |', '|---|---|---:|---:|---|']
    for p in NAMES:
        for v1,other in [('bls_v1','bls_pypi'),('bls_v1','bls_cpu'),('bls_v1','bls_gpu'),('tls_v1','gtls')]:
            ref='bls_v1_batch' if v1=='bls_v1' else v1;c=cc[p,ref,other]
            verdict='Supported within 5 pp' if c['comparable_detection'] else 'Not established; see recovery difference'
            text.append(f"| {NAMES[p]} | {METHODS[v1]} vs {METHODS[other]} | {ratios[p,'single',v1,other]['speedup']:.2f}× | {ratios[p,'batch16',v1,other]['speedup']:.2f}× | {verdict} |")
    text+=['','“Supported” means the one-sided 95% lower bound on paired v1-minus-comparator detection recall exceeds −5 percentage points, and the corresponding upper bound on the false-positive increase is below +5 points. It does not mean identical algorithms, exactly equal recall, or a universal sensitivity guarantee. Unmarked speed ratios are measured timing differences; they must not be advertised as demonstrated equivalent-sensitivity speedups.', '',
           '| Workload | Method | Correct primary period / 128 | Detected at correct period / 128 | False positives / 128 | Invalid held-out outputs |', '|---|---|---:|---:|---:|---:|']
    for p in NAMES:
        for m in METHODS:
            d=rr[p,m]
            text.append(f"| {NAMES[p]} | {METHODS[m]} | {d['period_recovered']} | {d['detected']} | {d['false_positives']} | {d['invalid_heldout']} |")
    text+=['', 'Each method’s detection threshold is the higher empirical 95th percentile of 128 independent calibration nulls. The held-out set contains 128 injections and 128 new nulls per observing pattern. The curves show 32 injections at each white-noise oracle SNR (6, 8, 10, 14), with 95% Wilson intervals. This SNR excludes the additional correlated residual and is neither native TLS SDE nor QLP pink-noise SNR. Achieved false-positive rates and paired differences are in [recovery_summary.csv](recovery_summary.csv), [recovery_by_snr.csv](recovery_by_snr.csv), and [paired_comparisons.csv](paired_comparisons.csv).', '',
           'Real cadence, controlled flux: the experiment uses public ZTF g/r times and relative errors, plus public QLP times/quality flags for one dense TESS sector and a controlled pair of separated sectors. Fluxes are simulated exposure-integrated batman transits with heteroscedastic Gaussian noise and an OU residual. Injections require at least five observed in-transit points and two observed events. Known band baselines and achromatic transits are supplied. These three cadence examples are not a random catalog sample, injections into observed flux, unconditional survey completeness, or a reproduction of the full current QLP pipeline.', '',
           'A long gap matters to timing because the longer baseline requires finer trial-period spacing to keep a transit aligned. TESS 200 s uses 4,133 BLS / 3,084 TLS periods; separated TESS sectors use 128,964 / 99,043; ZTF uses 423,781 / 312,064. BLS and TLS have different minimum periods, so comparisons are within each algorithm. A simulated sinusoid or noise does not invalidate a fixed-grid timing comparison on identical arrays; transits are needed here to establish recovery. GTLS’s mean-depth gate can also make flux values affect its execution time.', '',
           'Configuration selection used only 32 tuning injections per survey. The fastest complete choice within one recovery of the best in each family was retained, with close timings repeated. CPU candidates included Astropy, periodfind’s Rust implementation and fBLS; GPU BLS included periodfind. This identifies the strongest tested competitor for these workloads, not the fastest code that could exist. Selected versions, settings, exclusions and repeat evidence are in [selection.json](selection.json); operational choices are recorded separately when applicable.', '',
           'BLS gains come from reusing folded phase histograms for several phase offsets, cached compiled kernels and reusable memory, a vectorized maximum-bin scan, and a public batch API that reduces per-source dispatch/allocation work. Batch throughput has a separate recovery validation. Some tuned searches have different phase/duration discretization, so the total upgrade ratio is not a pure kernel ablation. PyPI 0.2.5 documents `noverlap` as unimplemented in its fast kernel: the adapter uses the documented repeated `dphi` calls, public reusable memory, a GPU maximum and one final transfer. No installed package source is changed.', '',
           'The external BLS implementations have additional numerical differences. Astropy and periodfind accept scalar duration bounds, approximated here with 16 logarithmic period chunks covering the same density prior. periodfind searches brightening and dimming boxes, whereas cuvarbase/Astropy are configured for dimmings; its public output does not expose a dip-only switch. periodfind’s long-lightcurve GPU branch has a fixed 64-bin array, so the dense TESS comparison uses a valid capped setting. Unchecked larger-bin calls crashed and are excluded. fBLS native-grid pilots and failures remain in the evidence; failures and timeouts do not supply speedup denominators.', '',
           'TLS gains combine architecture and host orchestration. cuvarbase folds into weighted phase bins, evaluates integrated templates and analytically solves weighted depths, then refines a limited candidate set against observations. GTLS sorts phase-folded samples, represents template widths in observation counts, estimates depth from an unweighted window mean and template overshoot, and evaluates weighted residuals. Epoch/duration grids, geometry, refinement and SDE construction differ. These are related template searches, not numerically identical algorithms. The fast cuvarbase TLS engine predates phase 5; the whole gain cannot be attributed to that phase.', '',
           'The separate [TLS component audit](../tls-profile-20260908/README.md) demonstrates substantial avoidable GTLS dispatch overhead. On its two retained diagnostic inputs, batching two Python/CuPy host operations makes GTLS about 5.8× faster while retaining the best periods; one operation is bit-identical and the other changes chi-square by a few parts in 10⁶ in absolute units. Those diagnostic patches are not the released competitor in this figure. The main comparison uses the unmodified public API, including its fast mode when selected by tuning. The remaining API ratio cannot be interpreted as the speed of an otherwise identical residual kernel.', '',
           'The earlier CPU TLS failures were concrete output/template edge cases in transitleastsquares 1.32. Sparse PS1/Gaia examples constructed a zero-sample transit template before searching. ZTF/Rubin completed the period search, then failed while constructing a zero-sample plotting model; ZTF had already found the correct 1.66894-day period. First-call failure times include compilation and are not successful CPU timings. This requested TLS comparison is v1 versus GTLS; those CPU failures are not converted to speed claims.', '',
           '| Workload | v1 BLS projected GPU cost / million | v1 TLS projected GPU cost / million | CPU hourly break-even for BLS |', '|---|---:|---:|---:|']
    for p in NAMES:
        ts={v['method']:v for v in tim['timings'] if v['profile']==p and v['mode']=='batch16'}
        text.append(f"| {NAMES[p]} | ${ts['bls_v1']['projected_gpu_usd_per_million']:.2f} | ${ts['tls_v1']['projected_gpu_usd_per_million']:.2f} | ${ratios[p,'batch16','bls_v1','bls_cpu']['cpu_break_even_hourly_usd']:.4f}/h |")
    text+=['', 'Costs use the actual A40 bundle price, $0.49/hour, and linearly project measured batch search time. A standalone CPU at the measured performance would need to cost below the listed break-even price to beat that GPU search cost. No standalone CPU rental was measured. These are search-only rental equivalents, not measured million-star jobs or complete QLP costs. Hardware: A40 and a 7.65-CPU-equivalent quota on an Intel Xeon Gold 6342 host; the 96 host logical CPUs are not the allocation.', '',
           'Provenance: frozen cuvarbase v1 commit `1032caf029570dc4841db1c594a2cbb1654e8fd8`; PyPI cuvarbase `0.2.5`; GTLS upstream commit `74e449c325792a763dde4fbffab98039c5e8c111`; periodfind commit `116b1b27c8db4c95035b5233efa6a1d21780afa5`. Source archives, the per-job installed-source hashes, input/output SHA256 values, controller exit records and every full periodogram are retained. [timing_summary.csv](timing_summary.csv) records timing boundaries and repetitions, [speedups.csv](speedups.csv) derives ratios/costs, and the analysis JSON files retain paired success vectors.', '',
           'Reproduce from the retained inputs and selected configurations with `scripts/benchmark_transit_recovery/worker.py` in the pinned modern/legacy environments; run manifests sequentially with `controller.py`. Regenerate verified statistics with `analyze.py --verify-arrays` and `analyze_timings.py --verify-arrays`, then `plot_main.py` and `write_report.py`, each with `--root analysis/transit-recovery-20260908`. All cloud resources must be terminated after evidence collection; the final rental ledger records actual elapsed rental and verified termination.']
    (r/'README.md').write_text('\n'.join(text)+'\n');print('Wrote README.md')


if __name__=='__main__':main()
